### PR TITLE
Three fixes for running realized Java classes in Verifier

### PR DESCRIPTION
**Pull request by tomas-oh**
This pull request will fix a few things related to running realized Java code in the Verifier:

* Running the VerifierInvocationAuditor will clear the cached classes in the BPClassLoader. Earlier you had to launch and terminate the Verifier to clear this cache and to be able to see if the errors in the realized Java classes had been fixed.
* Make the Verifier use core data types when marshalling values in. This enables us to use primitive data types (such as ints) in realized Structured data types. It also makes the realized code use the core type of User data types.
* Let the VerifierInvocationHandler use the setters if present when marshalling structured data types out. This seems to be the way this was intended to work, but must have been forgotten during the initial implementation. It is implemented like the way the getters are used when marshalling structs in. If a setter exists, use it. Otherwise fall back to direct field access.

See the individual commit messages for more details.

### CODE REVIEW

**Comment by keithbrown** [comment]
Thank you for submitting this pull request.  We'll check out the proposed changes.  

Regards,
Keith

**Comment by keithbrown** [comment]
Are the changes to address specific issues that already exist in the issue tracker (http://support.onefact.net)?  In order to maintain some history and requirements traceability, we always tie changes to issues in the bug system.  If they are for existing issues, let's note them here.  If no issue currently exists, let's open issues to record the problems and tie the new issues in here.  This is especially helpful for keeping tracking of when the fix is introduced into a release.

**Comment by tomas-oh** [comment]
No, but I have created three new issues in the tracker now. 

commit 2ba694a solves https://support.onefact.net/issues/8688
commits f534689 and 6075d21 solve https://support.onefact.net/issues/8689
commit 241bf98 solves https://support.onefact.net/issues/8690

**Comment by keithbrown** [comment]
Tomas,

Thank you for creating the issues in the bug tracker and linking them here.

I'm looking forward to merging in these updates.  So far the updates look good.  Do you have test steps or a test model that I can use as I test for promotion?

**Comment by tomas-oh** [comment]
I uploaded the test project I have been using in the issue tracker for issue [#8690](https://support.onefact.net/issues/8690). The project was used to test both #8689 and #8690, so all commits related to the two must be applied for the test to work with no errors.

**Pull request merged**
