### PR TITLE
job #9041 updated table 5.3.3

### PR DESCRIPTION
**Pull request by rmulvey**
Cort and I were discussing rules around dialect type assignment and in doing reviewed table 5.3.3. A couple small, but important changes were made. Note that this table is useful in combination with the diagram, figure 1, in the MASL Modeling and Conversion Guide.

### CODE REVIEW

**Comment by leviathan747** [comment]
I think I am ok with this change... but it was worded in that specific way for a reason. The reason is that the set of domain components plus the set of non domain components is not the set of all components. This table of default values applies to OAL dialect xtUML projects as well. by non-domain component I mean any component that is not a domain component which is not the same as saying project component.

That being said, if the reader is thinking in the context of only MASL domain and project components, then the change is ok.

**Comment by rmulvey** [comment]
Ok, makes sense. I think the target audience here is masl users. I am planning to essentially copy/paste this table in the MASL Modeling and Conversion Guide. i think this wording is good there.

**Comment by leviathan747** [comment]
Perhaps leave it as is in the engineering note and change the wording for the MASL guide

**Comment by rmulvey** [comment]
can't do that though, because pasrt of the change is an actual error. The "provided port" changed to "requered port", that was a cut/paste error I think

**Comment by leviathan747** [comment]
I don't think it's a huge deal. And the changes makes it easier to understand. I will merge it

**Pull request merged**
