### PR TITLE
Fix issue #8813 - Assign Signal visible for Instance State Machines 

### PR DESCRIPTION
**Pull request by perojonsson**
Updated the filtering for "Assign Signal" operation so that it is not shown for Instance State Machines.

This pull request requires xtuml/models#87 for test to pass.

### CODE REVIEW

**Comment by nmohamad** [comment]
There are failures in Core I, and Core II

Core I 2F
Core II  2E, 18F

I looked at the changes, and this change does not look clean for me:

select one cls related by self->SM_SM[R505]->SM_ASM[R517]->O_OBJ[R519];
    //if (empty cls)
    //  select one cls related by self->SM_SM[R505]->SM_ISM[R517]->O_OBJ[R518];
    //end if;
    select one packageableElem related by cls->PE_PE[R8001];
    select one package related by packageableElem->EP_PKG[R8000];

**Comment by keithbrown** [comment]
The test failures in Core I and II are not necessarily related to this pull's code change.  @nmohamad should test current master to see what those results are.

**Comment by perojonsson** [comment]
The comment regarding non clean change is valid, the relevant code should have been
```
select one cls related by self->SM_SM[R505]->SM_ASM[R517]->O_OBJ[R519];
if (empty cls)
  return false;
end if;
select one packageableElem related by cls->PE_PE[R8001];
select one package related by packageableElem->EP_PKG[R8000];
```
Will update.

**Comment by nmohamad** [comment]
I ran tests against master today. 
Core I, Core II  gives same failures, so Suites are passed.

**Pull request merged**
