### PR TITLE
8643 combined referentials

### PR DESCRIPTION
**Pull request by lwriemen**
Modifications to combine and split of referential attributes for #8643

### CODE REVIEW

**Comment by keithbrown** [comment]
Lee, thanks for submitting the pull request.   I've assigned it to myself.

**Comment by keithbrown** [comment]
@lwriemen, this is an important change and we want it to be very clear what has changed functionally.  It's going to be a bit painful, but I'm going to ask you to undo all the non-functional formatting changes (even though they are formatting fixes) so that it is very clear what the functional changes are.

**Comment by lwriemen** [comment]
OK. Undid. FYI, you can pass diff options to the command line git diff. e.g., In this case where the non-functional formatting was whitespace changes, git diff -b -w [<commit>] [<commit>]

**Comment by lwriemen** [comment]
Just found this tip: add ?w=1 to the URL to see the diff with whitespace ignored.

**Pull request merged**
