### PR TITLE
11949 association phrases

### PR DESCRIPTION
**Pull request by lwriemen**
If anyone sees a better way of doing this, please suggest it. My bridge from ooaofooa to ooaofgraphics seems a little clumsy, but maybe it's OK. I also made another suggestion in the INT that might need to be given consideration.

### CODE REVIEW

**Comment by leviathan747** [comment]
Have you considered running this code from the model loader? Check out for example `upgradeElementOrder` in `org.xtuml.bp.io.core/src/org/xtuml/bp/io/core/ImportHelper.java:2259`. This adds order to elements like attributes from older models which didn't have explicit order. This method is called from `finishComponentLoad` which is generated from `org.xtuml.bp.io.core/arc/gen_import_java.inc:886`. That method operates on a `List` called `loadedInstances` but there is also `loadedGraphicsInstances` which contains all the ooaofgraphics model instances that were loaded. Seems like this would greatly reduce the changeset.

**Comment by lwriemen** [comment]
The changes do run from the model loader, but I was looking for a better way. Thank you; I'll check into this. One concern I have is that I might stomp on a valid Connector <-> End value. I identified a singlet occurrence, which might be valid for some model elements. If anyone can tell me that the enumeration value, End::Additional, is invalid for floating text on a connector, then I can just run the checking from the ooaofgraphics with no involvement of ooaofooa.

**Comment by lwriemen** [comment]
Actually, I think I could use GD_GE::OOA_ID and element of with an existing path back to ooaofooa to limit the connector checks to certain ooaofooa elements, but the definition of End::Additional might still be helpful.

**Comment by cmccausl** [comment]
If we can limit this to ooaofgraphics, it avoids the communication between
and reduces risk on the semantic model.  That would be nice.

**Comment by lwriemen** [comment]
I don't understand what you mean by "risk on the semantic model".

**Comment by cmccausl** [comment]
changing oofofooa code

**Comment by lwriemen** [comment]
This should be ready now. Looks too easy now.

**Comment by cortlandstarrett** [comment]
Nice.  I will merge this into my working branch, run a server build and then do some testing over the weekend.

**Pull request merged**
