### PR TITLE
#9461 fixed assignability of component types to sequence types

### PR DESCRIPTION
**Pull request by JanKoehnlein**

### CODE REVIEW

**Comment by keithbrown** [comment]
I'm still trying to verify but I notice that some of the changes are to .xtend files in the UI plugin.  IIRC this was the spot where we had to commit the generated Java file(s) because of the jar-in-jar build issue.  When you build the plug-in do you notice any dirty Java files that should be committed?

**Comment by JanKoehnlein** [comment]
AFAIR, only the classes that are referred to by other plug-ins had to be converted to Java, which is not the case for those I changed. So I expect no build issues. Please notify me if you encounter problems.
--
Dr. Jan Köhnlein
jan.koehnlein@typefox.io

TypeFox GmbH
Am Germaniahafen 1
24143 Kiel

Phone: +49 151 17396687
Skype: jankoehnlein
Twitter: jankoehnlein

Sitz: Kiel, Registergericht: Amtsgericht Kiel, HRB 17385
Geschäftsführer: Sven Efftinge, Moritz Eysholdt, Dr. Jan Köhnlein

**Comment by keithbrown** [comment]
I'm having a build issue locally.

Description	Resource	Path	Location	Type
The import org.xtuml.bp.xtext.masl.parser.antlr.lexer.jflex.MASLFlexer cannot be resolved	JFlexBasedInternalMASLLexer.java	/org.xtuml.bp.xtext.masl.ide/src-gen/org/xtuml/bp/xtext/masl/ide/contentassist/antlr/lexer/jflex	line 14	Java Problem

It looks to me like MASLFlexer.java is a generated file that is not being created for some reason.

**Comment by JanKoehnlein** [comment]
There is a .gitignore for it, pushed in 84781ccb9586b39dcfca339c9d32eb6e67f7e5fa
Don't see why this would make any sense.
--
Dr. Jan Köhnlein
jan.koehnlein@typefox.io

TypeFox GmbH
Am Germaniahafen 1
24143 Kiel

Phone: +49 151 17396687
Skype: jankoehnlein
Twitter: jankoehnlein

Sitz: Kiel, Registergericht: Amtsgericht Kiel, HRB 17385
Geschäftsführer: Sven Efftinge, Moritz Eysholdt, Dr. Jan Köhnlein

**Comment by keithbrown** [comment]
Should it be in the .gitignore or not?  Levi showed me how to use the "Run As > MWE2 workflow" on git/bridgepoint/src/org.xtuml.bp.xtext.masl.parent/org.xtuml.bp.xtext.masl/src/org/xtuml/bp/xtext/masl/GenerateMASL.mwe2 and now MASLFlexer.java appeared.

**Comment by JanKoehnlein** [comment]
As the workflow is currently not run in the build and other files depend on MASLFlexer.java the build will fail.
So the .gitignore is wrong IMHO. But maybe you should ask Travis why he added it.
I'd remove the .gitignore and push the MASLFlexer.java.
--
Dr. Jan Köhnlein
jan.koehnlein@typefox.io

TypeFox GmbH
Am Germaniahafen 1
24143 Kiel

Phone: +49 151 17396687
Skype: jankoehnlein
Twitter: jankoehnlein

Sitz: Kiel, Registergericht: Amtsgericht Kiel, HRB 17385
Geschäftsführer: Sven Efftinge, Moritz Eysholdt, Dr. Jan Köhnlein

**Pull request merged**
