### PR TITLE
9001 9047 8808 9057 promotion

### PR DESCRIPTION
**Pull request by leviathan747**
This promotion resolves issues #9001, #9047, #8808, and #9057

Testing for #9047 is deferred because it is not required for the current release. #9047 will remain open until it is fully implemented and tested.

Possible issues:
- I saw a Threading exception on opening of some activities
- State activities are missing the signature label

The tests for these issues are scattered around in notes. I know there are tests for #9001 and #8808. I'm not sure about #9057.

### CODE REVIEW

**Comment by rmulvey** [comment]
BTW here is a list of the issues that are resolved in this pull request:
9001 - Validating cell editor for Data Type Definition
8808 - deprecate 'function' keyword in MASL
9121 - Open masl action bodies in a single-buffer editor

The following issues are related to the muti-buffer editor, and while this issue indirectly resolves them by using a single-buffer editor, I am deferring their testing and closure to a future release (project codename Grip) where the multi-buffer edit may be enabled again.
8412 - Parameter Synchronization is required for the multi-buffer masl editor
9047 - Have the xtext editor indexing to the selected action body when opened by the user
9072 - (ServicePro)  Adding parameter to a MASL service gives an error.
9057 - Adding parameter to a MASL service gives an error.

**Comment by leviathan747** [comment]
Issue 3 (above) resolved

**Comment by leviathan747** [comment]
I'm seeing another issue. Appears to be related to 8808. Warnings appear on my project saying "DomainServiceDefinition elements should be defined in a file with extension '.fn' or '.masl'." The file extension .fn is not used anymore.

**Comment by leviathan747** [comment]
See here for build fix comments https://github.com/leviathan747/bridgepoint/pull/18

**Pull request merged**
